apiVersion: v1
kind: Service
metadata:
  name: sabora-service
spec:
  type: NodePort
  selector:
    app: sabora-backend
  ports:
    - protocol: TCP
      port: 4100
      targetPort: 4100
      nodePort: 30200